# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - expose-pythons
      - init-pants
      - pyenv
      - run-tox
    groups:
      gha-deps:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
    target-branch: "depbot"
    assignees:
      - sureshjoshi
